name = "remix-boilerplate" #todo need real data
compatibility_date = "2022-01-14"

account_id = "93e39c248caa03a01ab11bc4d73875cf" #todo need real data
workers_dev = true

main = "build/index.js"

[env.production]
route = "https://remix.hungvu.work/*" #todo need real data
workers_dev = false

[site]
bucket = "./public"

[build]
command = "npm run build"
