name = "remix-boilerplate" #todo need real data
compatibility_date = "2022-01-14"

account_id = "93e39c248caa03a01ab11bc4d73875cf" #todo need real data
workers_dev = true

main = "build/index.js"

[vars]
BRAND = "Remix Boilerplate" #todo need real data
API_BASE_URL = "https://api.remix.com" #todo need real data
IR_URL = "https://ir.remix.run"
HOST = "http://127.0.0.1"

[env.production]
route = "https://remix.hungvu.work/*" #todo need real data
workers_dev = false

[env.production.vars]
BRAND = "Remix Boilerplate" #todo need real data
API_BASE_URL = "https://api.remix.com" #todo need real data
IR_URL = "https://ir.remix.run"
HOST = "http://127.0.0.1"

[site]
bucket = "./public"

[build]
command = "npm run build"
